version: '3'

services:
  main:
    image: fitiavana07/flask:${VERSION_MAIN:-latest}
    build:
      context: ./main
      dockerfile: Dockerfile

  dev:
    image: fitiavana07/flask:${VERSION_DEV:-dev}
    build:
      context: ./dev
      dockerfile: Dockerfile
